import QtQuick 2.0

//一个卡片model样本
ListModel {
    id: cardModel
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card1
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card2
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card3
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card4
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card5
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card6
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card7
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card8
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card9
    ListElement {
        title: 1
        content: 2
        cardImag: 3
        userName: 4
        headImag: 5
        createTime: 6
    } //card10
}
